AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 20
    Runtime: java21
    MemorySize: 512
    Architectures:
      - x86_64
Resources:
  JumpRecognizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: jump-pulse-recognizer
      Handler: telran.monitoring.App::handleRequest
      Policies:
        - Statement:
            - Effect: Allow
              Resource: '*' 
              Action:
              - dynamodb:*
        - S3FullAccess # Новая политика для работы с S3
      Environment:
        Variables:
          LOGGER_LEVEL: finest
          STREAM_NAME: !Ref JumpDataStream
          STREAM_CLASS_NAME: telran.monitoring.DynamoDbStreamJumpPulseData
          LATEST_VALUES_SAVER_CLASS: telran.monitoring.LatestDataSaverS3 # Использование нового класса
          S3_BUCKET_NAME: "your-s3-bucket-name" # Переменная среды для S3
      Events:
        DynamoDbItemInsert:
          Type: DynamoDB
          Properties:
            StartingPosition: LATEST
            BatchSize: 1
            Stream: !GetAtt PulseValuesStream.StreamArn
            FilterCriteria:
              Filters:
              - Pattern: '{"eventName": ["INSERT"]}'

  PulseValuesReducerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: pulse-values-reducer
      Handler: telran.monitoring.AppReducer::handleRequest
      Policies:
        - Statement:
            - Effect: Allow
              Resource: '*' 
              Action:
              - dynamodb:*
        - S3FullAccess # политика для работы с S3
      Environment:
        Variables:
          LOGGER_LEVEL: finest
          STREAM_NAME: !Ref AvgValuesDataStream
          REDUCING_SIZE: 5
          REDUCING_TIME_WINDOW: 600000
          STREAM_CLASS_NAME: telran.monitoring.DynamoDbStreamSensorData
          LATEST_VALUES_SAVER_CLASS: telran.monitoring.LatestDataSaverS3
          S3_BUCKET_NAME: "my-s3-bucket" # Переменная среды для S3
      Events:
        DynamoDbItemInsert:
          Type: DynamoDB
          Properties:
            StartingPosition: LATEST
            BatchSize: 1
            Stream: !GetAtt PulseValuesStream.StreamArn
            FilterCriteria:
              Filters:
              - Pattern: '{"eventName": ["INSERT"]}'

  PulseValuesStream:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: pulse_values
      KeySchema:
        - AttributeName: patientId
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: patientId
          AttributeType: N
        - AttributeName: timestamp
          AttributeType: N
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  JumpDataStream:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: patientId
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: patientId
          AttributeType: N
        - AttributeName: timestamp
          AttributeType: N     
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  AvgValuesDataStream:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: patientId
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: patientId
          AttributeType: N
        - AttributeName: timestamp
          AttributeType: N     
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE        

  AbnormalValuesDataStream:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: patientId
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: patientId
          AttributeType: N
        - AttributeName: timestamp
          AttributeType: N     
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE 

  PulseAbnormalValuesRecognizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: abnormal-values-recognizer
      Handler: telran.monitoring.AppAbnormalRecognizer::handleRequest
      FunctionName: abnormal-values-recognizer
      Policies:
        - Statement:
            - Effect: Allow
              Resource: '*' 
              Action:
              - dynamodb:*
      Environment:
        Variables:
          LOGGER_LEVEL: finest
          STREAM_NAME: !Ref AbnormalValuesDataStream
          RANGE_PROVIDER_CLASS: telran.monitoring.RangeProviderClientHttp
          STREAM_CLASS_NAME: telran.monitoring.DynamoDbAbnormalPulseValueStream
          RANGE_PROVIDER_URL: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/range/"
      Events:
        DynamoDbItemInsert:
          Type: DynamoDB
          Properties:
            StartingPosition: LATEST
            BatchSize: 1
            Stream: !GetAtt PulseValuesStream.StreamArn
            FilterCriteria:
              Filters:
              - Pattern: '{"eventName": ["INSERT"]}'      

  RangeDataProviderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: range-data-provider
      Handler: telran.monitoring.AppRangeDataProvider::handleRequest
      Environment: 
        Variables:
          DB_PASSWORD: 12345.Com
      Events:
        RangeDataProvider:
          Type: Api 
          Properties:
            Path: /range
            Method: get

Outputs:
  RangeDataProviderApi:
    Description: "API Gateway endpoint URL for Prod stage for Range Data Provider Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/range/"
